//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class DynamicTableViewWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(DynamicTableView), typeof(TableView));
		L.RegFunction("SetCellSizeFunc", SetCellSizeFunc);
		L.RegFunction("SetCellTypeIndex", SetCellTypeIndex);
		L.RegFunction("InitComponent", InitComponent);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("m_other_cell_items", get_m_other_cell_items, set_m_other_cell_items);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCellSizeFunc(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DynamicTableView obj = (DynamicTableView)ToLua.CheckObject<DynamicTableView>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetCellSizeFunc(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetCellTypeIndex(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			DynamicTableView obj = (DynamicTableView)ToLua.CheckObject<DynamicTableView>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			obj.SetCellTypeIndex(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int InitComponent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			DynamicTableView obj = (DynamicTableView)ToLua.CheckObject<DynamicTableView>(L, 1);
			obj.InitComponent();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_m_other_cell_items(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DynamicTableView obj = (DynamicTableView)o;
			UnityEngine.GameObject[] ret = obj.m_other_cell_items;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_other_cell_items on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_m_other_cell_items(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			DynamicTableView obj = (DynamicTableView)o;
			UnityEngine.GameObject[] arg0 = ToLua.CheckObjectArray<UnityEngine.GameObject>(L, 2);
			obj.m_other_cell_items = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index m_other_cell_items on a nil value");
		}
	}
}

