//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class System_Security_Cryptography_MD5Wrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(System.Security.Cryptography.MD5), typeof(System.Security.Cryptography.HashAlgorithm));
		L.RegFunction("Create", Create);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Create(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				System.Security.Cryptography.MD5 o = System.Security.Cryptography.MD5.Create();
				ToLua.PushObject(L, o);
				return 1;
			}
			else if (count == 1)
			{
				string arg0 = ToLua.CheckString(L, 1);
				System.Security.Cryptography.MD5 o = System.Security.Cryptography.MD5.Create(arg0);
				ToLua.PushObject(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: System.Security.Cryptography.MD5.Create");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

