//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_EventSystems_EventTrigger_EntryWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.EventSystems.EventTrigger.Entry), typeof(System.Object));
		L.RegFunction("New", _CreateUnityEngine_EventSystems_EventTrigger_Entry);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("eventID", get_eventID, set_eventID);
		L.RegVar("callback", get_callback, set_callback);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_EventSystems_EventTrigger_Entry(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityEngine.EventSystems.EventTrigger.Entry obj = new UnityEngine.EventSystems.EventTrigger.Entry();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityEngine.EventSystems.EventTrigger.Entry.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_eventID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.EventSystems.EventTrigger.Entry obj = (UnityEngine.EventSystems.EventTrigger.Entry)o;
			UnityEngine.EventSystems.EventTriggerType ret = obj.eventID;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eventID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_callback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.EventSystems.EventTrigger.Entry obj = (UnityEngine.EventSystems.EventTrigger.Entry)o;
			UnityEngine.EventSystems.EventTrigger.TriggerEvent ret = obj.callback;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index callback on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_eventID(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.EventSystems.EventTrigger.Entry obj = (UnityEngine.EventSystems.EventTrigger.Entry)o;
			UnityEngine.EventSystems.EventTriggerType arg0 = (UnityEngine.EventSystems.EventTriggerType)ToLua.CheckObject(L, 2, typeof(UnityEngine.EventSystems.EventTriggerType));
			obj.eventID = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index eventID on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_callback(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.EventSystems.EventTrigger.Entry obj = (UnityEngine.EventSystems.EventTrigger.Entry)o;
			UnityEngine.EventSystems.EventTrigger.TriggerEvent arg0 = (UnityEngine.EventSystems.EventTrigger.TriggerEvent)ToLua.CheckObject<UnityEngine.EventSystems.EventTrigger.TriggerEvent>(L, 2);
			obj.callback = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index callback on a nil value");
		}
	}
}

