//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_AnimatorTransitionInfoWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityEngine.AnimatorTransitionInfo), null);
		L.RegFunction("IsName", IsName);
		L.RegFunction("IsUserName", IsUserName);
		L.RegFunction("New", _CreateUnityEngine_AnimatorTransitionInfo);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("fullPathHash", get_fullPathHash, null);
		L.RegVar("nameHash", get_nameHash, null);
		L.RegVar("userNameHash", get_userNameHash, null);
		L.RegVar("durationUnit", get_durationUnit, null);
		L.RegVar("duration", get_duration, null);
		L.RegVar("normalizedTime", get_normalizedTime, null);
		L.RegVar("anyState", get_anyState, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityEngine_AnimatorTransitionInfo(IntPtr L)
	{
		UnityEngine.AnimatorTransitionInfo obj = new UnityEngine.AnimatorTransitionInfo();
		ToLua.PushValue(L, obj);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)ToLua.CheckObject(L, 1, typeof(UnityEngine.AnimatorTransitionInfo));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsName(arg0);
			LuaDLL.lua_pushboolean(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IsUserName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)ToLua.CheckObject(L, 1, typeof(UnityEngine.AnimatorTransitionInfo));
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.IsUserName(arg0);
			LuaDLL.lua_pushboolean(L, o);
			ToLua.SetBack(L, 1, obj);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_fullPathHash(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			int ret = obj.fullPathHash;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index fullPathHash on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_nameHash(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			int ret = obj.nameHash;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index nameHash on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_userNameHash(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			int ret = obj.userNameHash;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index userNameHash on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_durationUnit(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			UnityEngine.DurationUnit ret = obj.durationUnit;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index durationUnit on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_duration(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			float ret = obj.duration;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index duration on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_normalizedTime(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			float ret = obj.normalizedTime;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index normalizedTime on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_anyState(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityEngine.AnimatorTransitionInfo obj = (UnityEngine.AnimatorTransitionInfo)o;
			bool ret = obj.anyState;
			LuaDLL.lua_pushboolean(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index anyState on a nil value");
		}
	}
}

