//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ReceiveGIWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ReceiveGI));
		L.RegVar("Lightmaps", get_Lightmaps, null);
		L.RegVar("LightProbes", get_LightProbes, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.ReceiveGI>.Check = CheckType;
		StackTraits<UnityEngine.ReceiveGI>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ReceiveGI arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.ReceiveGI), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Lightmaps(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ReceiveGI.Lightmaps);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_LightProbes(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ReceiveGI.LightProbes);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ReceiveGI o = (UnityEngine.ReceiveGI)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

